---
title: "Monte Carlo"
runtime: shiny
output:
  flexdashboard::flex_dashboard:
    orientation: rows
    source_code: embed
---


```{r setup, message = FALSE}
library(tidyverse)
library(highcharter)
library(tidyquant)
library(timetk)
library(scales)
library(readxl)
```

Sidebar {.sidebar}
=====================================
  
```{r}

fluidRow(
  column(10,
  numericInput("w1", "US Large Cap Portf. %", 27, min = 1, max = 100))
)  

fluidRow(
  column(10,
  numericInput("w2", "US Small Cap Portf. %", 9, min = 1, max = 100))
)

fluidRow(
  column(10,
  numericInput("w3", "International Developed Equity Portf. %", 13.5, min = 1, max = 100))
)

fluidRow(
  column(10,
  numericInput("w4", "Emerging Equity Portf. %", 4.5, min = 1, max = 100))
)

fluidRow(
  column(10,
  numericInput("w5", "TIPS Portf. %", 3.27, min = 1, max = 100))
)

fluidRow(
  column(10,
  numericInput("w6", "Broad Fixed Income Portf. %", 1.23, min = 1, max = 100))
)

fluidRow(
  column(10,
  numericInput("w7", "US Treasury Portf. %", 8.08, min = 1, max = 100))
)

fluidRow(
  column(10,
  numericInput("w8", "Investment Grade Credit Portf. %", 3.35, min = 1, max = 100))
)

fluidRow(
  column(10,
  numericInput("w9", "Agency Mortgage Backed Securities Portf. %", 3.91, min = 1, max = 100))
)

fluidRow(
  column(10,
  numericInput("w10", "High Yield Portf. %", 2.6, min = 1, max = 100))
)

fluidRow(
  column(10,
  numericInput("w11", "Private Equity Portf. %", 12, min = 1, max = 100))
)

fluidRow(
  column(10,
  numericInput("w12", "Real Estate Portf. %", 8, min = 1, max = 100))
)

fluidRow(
  column(10,
  numericInput("w13", "Cash Portf. %", 3.56, min = 1, max = 100))
)

fluidRow(
  column(5,
  numericInput("sim_years", "Years", 30, min = 5, max = 50, step = 5)),
  column(5,
  numericInput("sims", "Sims", 500, min = 100, max = 100000, step = 100))
)

actionButton("go", "Submit")
```


```{r}

jpm <- read_excel("JPM.xlsx", sheet = "return") 
corr_matrix <- read_excel("JPM.xlsx", sheet = "corr_matrix", col_names = FALSE)

weights <- eventReactive(input$go, {
  w <- c(input$w1/100, input$w2/100, input$w3/100, input$w4/100, input$w5/100,
         input$w6/100, input$w7/100, input$w8/100, input$w9/100, input$w10/100, 
         input$w11/100, input$w12/100, input$w13/100)
})

mean_port_return <- eventReactive(input$go, {
  crossprod(weights(), jpm$mean_return)
})

stddev_port_return <- eventReactive(input$go, {
  wv <- weights() * jpm$volatility
  port_var <- t(wv) %*% as.matrix(corr_matrix) %*% wv
  stddev_port_return <- sqrt(port_var)
})

simulation_accum <- function(init_value, N, mean, stdev) {
  tibble(returns = c(init_value, 1 + rnorm(N, mean, stdev))) %>%
    mutate(growth = accumulate(returns, function(x, y) x * y)) %>%
    select(growth)
}

simulation_returns <- function(init_value, N, mean, stdev) {
  tibble(returns = c(init_value, 1 + rnorm(N, mean, stdev))) %>%
#    mutate(growth = accumulate(returns, function(x, y) x * y)) %>%
    select(returns)
}

sims <- eventReactive(input$go, {input$sims})

monte_carlo_sim <- eventReactive(input$go, { 
  
  sims <- sims()
  
  starts <-  
    rep(1, sims) %>%
    set_names(paste("sim", 1:sims, sep = ""))
  
  # mc <- map_dfc(starts, 
  #               simulation_accum, 
  #               input$sim_years, 
  #               mean = mean_port_return(), 
  #               stdev = stddev_port_return()
  #               ) %>%
  # mutate(year = seq(1:nrow(.))) %>%
  # select(year, everything()) %>%
  # `colnames<-`(c("year", names(starts))) %>%
  # gather(sim, growth, -year) %>%
  # group_by(sim) %>% 
  # mutate_at(vars(-sim), funs(round(., 2)))
  
  mc <- map_dfc(starts, 
                simulation_returns, 
                input$sim_years, 
                mean = mean_port_return(), 
                stdev = stddev_port_return()
                ) %>%
  mutate(year = seq(1:nrow(.))) %>%
  select(year, everything()) %>%
  `colnames<-`(c("year", names(starts))) %>%
  gather(sim, returns, -year) %>%
  group_by(sim) %>% 
  mutate_at(vars(-sim), funs(round(., 2)))
  
})

```

Simulated Growth
=====================================  

Row {data-height=600, .tabset}
-----------------------------------------------------------------------

### Sim Vis highcharter

```{r}
# renderHighchart(
#   hchart( monte_carlo_sim(), 
#        type = 'line', 
#        hcaes(y = growth,
#              x = year,
#              group = sim)) %>% 
#   hc_title(text = paste(sims(), "Simulations", sep = " ")) %>%
#   hc_xAxis(title = list(text = "Years")) %>%
#   hc_yAxis(title = list(text = "Dollar Growth"),
#            labels = list(format = "${value}")) %>%
#   hc_add_theme(hc_theme_flat()) %>%
#   hc_exporting(enabled = TRUE) %>% 
#   hc_legend(enabled = FALSE)
# )
```

```{r}
renderHighchart(
  hchart( monte_carlo_sim(), 
       type = 'line', 
       hcaes(y = returns,
             x = year,
             group = sim)) %>% 
  hc_title(text = paste(sims(), "Simulations", sep = " ")) %>%
  hc_xAxis(title = list(text = "Years")) %>%
  hc_yAxis(title = list(text = "Annual Investment Return"),
           labels = list(format = "${value}")) %>%
  hc_add_theme(hc_theme_flat()) %>%
  hc_exporting(enabled = TRUE) %>% 
  hc_legend(enabled = FALSE)
)
```

Row
-------------------------------------

### Min, Max, Median Sim

```{r}
# renderHighchart({
#  
# sim_summary <- 
#   monte_carlo_sim() %>%
#   summarise(final = last(growth)) %>% 
#   summarise(
#             max = max(final), 
#             min = min(final),
#             median = median(final))
# 
# mc_max_med_min <- 
#   monte_carlo_sim() %>%
#   filter(
#       last(growth) == sim_summary$max || 
#       last(growth) == sim_summary$median ||
#       last(growth) == sim_summary$min)
# 
#   hchart(mc_max_med_min, 
#        type = 'line', 
#        hcaes(y = growth,
#              x = year,
#              group = sim)) %>% 
#   hc_title(text = "Min Max Median Simulations") %>%
#   hc_xAxis(title = list(text = "years")) %>%
#   hc_yAxis(title = list(text = "dollar growth"),
#            labels = list(format = "${value}")) %>%
#   hc_add_theme(hc_theme_flat()) %>%
#   hc_exporting(enabled = TRUE) %>% 
#   hc_legend(enabled = FALSE)
# })
```

